version: '3.9'
services:
  idendtity_db:
    container_name: identity_database
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-school_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /data/postgres
    volumes:
      - identity_postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  identity_postgres:
