version: '3.9'
services:
  postgres:
    container_name: school_database
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-school_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /data/postgres
    volumes:
      - school_postgres:/data/postgres
    ports:
      - "5434:5432"
    restart: unless-stopped
  
volumes:
  school_postgres:
